[project]
site_name = "test-copier-uv"
site_url = "https://gauthamchettiar.github.io/test_copier_uv"
docs_dir = "docs"
site_dir = "public"
nav = [
    { "Home" = "index.md" },
    { "API Reference" = [{ "Hello" = "api/hello.md" },] },
    { "Development" = [
        { "Changelog" = "changelog.md" },
        { "Contributing" = "contributing.md" },
        { "Code of Conduct" = "code_of_conduct.md" },
        { "License" = "license.md" },
    ] },
]

[project.theme]
features = [
    "content.code.copy"
]

[project.markdown_extensions.pymdownx.highlight]
anchor_linenums = true
line_spans = "__span"
pygments_lang_class = true
[project.markdown_extensions.pymdownx.inlinehilite]
[project.markdown_extensions.pymdownx.snippets]
[project.markdown_extensions.pymdownx.superfences]

[project.markdown_extensions.admonition]
[project.markdown_extensions.pymdownx.details]

[project.plugins.mkdocstrings.handlers.python]
inventories = ["https://docs.python.org/3/objects.inv"]
paths = ["src"]

[project.plugins.mkdocstrings.handlers.python.options]
docstring_style = "google"
inherited_members = true
show_source = false

[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to system preference"
